added initial condition file as argument

diff --git a/test-particle-stability-adjust-planets/spock-stability/submit-all-jobs b/test-particle-stability-adjust-planets/spock-stability/submit-all-jobs
--- a/test-particle-stability-adjust-planets/spock-stability/submit-all-jobs
+++ b/test-particle-stability-adjust-planets/spock-stability/submit-all-jobs
@@ -2,7 +2,16 @@
 
 ## SUBMIT IN BATCHES OF 500
 
+while getopts ":a:" opt; do
+  case $opt in
+    a) ic_name="$OPTARG"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
 for fsim in {0..159500..500}
 do
-	qsub -v nsys=500,first_sim=$fsim sunnyvale-systems-predict-stability-qsub-script
+    qsub -v ic_file=$ic_name,nsys=500,first_sim=$fsim sunnyvale-systems-predict-stability-qsub-script
 done
